#!/bin/sh
#
# Creates symlinks to $BIN

for entry in $(du -a "${SCRIPTS}" | awk '{print $2}'); do
   if [ -f "${entry}" ] && [ $(file --mime-type -b ${entry}) != "text/plain" ]; then
      echo $(basename "${entry}")
      ln -sf "${entry}" "${BIN}"/$(basename "${entry}")
   fi
done

