#!/bin/bash
#
# Add torrent to transmission-daemon
#

proc_trans_da=$(pgrep -x transmission-da)

if [[ ${proc_trans_da} ]]; then
   transmission-daemon
   dunstify "Starting transmission daemon ..."
   sleep 3
   transmission-remote -a "$@"
   dunstify "Torrent added."
fi
