#!/bin/bash
#
# Start/stop transmission daemon
#

main()
{
   case "$1" in
      "start")
         t_start
         ;;
      "stop")
         pkill transmission-da && dunstify "Stopping transmission daemon ..."
         ;;
      *)
         exit 1
         ;;
   esac
}

t_start()
{
   proc_trans_da=$(pgrep -x transmission-da)
   if [[ ! ${proc_trans_da} ]]; then
      transmission-daemon
      dunstify "Starting transmission daemon ..."
   fi
}


#-------------------------------------------------

main "$@"
