#!/bin/bash
#
# Display the numpad state (on/off if numlock is pressed)
#

type="${BLOCK_INSTANCE:-caps}"
lockLine=$(xset -q | grep "Num Lock")
capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

if [[ "${type}" = "caps" ]]; then
  checkLock="${capsLock}"
elif [[ "${type}" = "num" ]]; then
  checkLock="${numLock}"
elif [[ "${type}" = "scroll" ]]; then
  checkLock="${scrollLock}"
else
  exit
fi

if [[ "${checkLock}" = "on" ]]; then
  echo " on"
else
  echo " off"
fi
