#!/bin/bash
#
# Display the system locale
#

locale_info=$(localectl)
locale_name=$(echo "${locale_info}" | grep "System Locale" | awk -F '=' '{print $2}' | cut -c 1-2)

if [[ "${locale_name}" ]]; then
  echo " ${locale_name}"
fi
