#!/bin/bash
# Based on http://openweathermap.org/current
# Check on http://openweathermap.org/find
#
# Font Awesome(no emoji):      
#
# Display the weather on current city.
# Need and account on the above addres.
#
# Test(run in teminal)=echo $(curl -s "http://api.openweathermap.org/data/2.5/weather?id=675810&appid=73bfabc743b0e57a3445c0bdd6199f19&units=metric")
#

api_key="73bfabc743b0e57a3445c0bdd6199f19"
city_id="${BLOCK_INSTANCE}"

icon_sunny="☀️"
icon_cloudy="☁️"
icon_rainy="🌧️"
icon_storm="🌩️"
icon_snow="🌨️"
icon_fog="🌫️"

symbol_celsius="℃"

weather_url="http://api.openweathermap.org/data/2.5/weather?id=${city_id}&appid=${api_key}&units=metric"
weather_info=$(curl --silent ${weather_url})
weather_main=$(echo ${weather_info}|grep -o -e '\"main\":\"[a-Z]*\"'| awk -F ':' '{print $2}' | tr -d '"')
weather_temp=$(echo ${weather_info}|grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
weather_city=$(echo ${weather_info}|grep -o -e '\"name\":\"[a-Z]*\"'| awk -F ':' '{print $2}' | tr -d '"')

get_weather()
{
   echo "$(echo "$1" | grep "$2")"
}

if [[ "$(get_weather "${weather_main}" "Snow")" ]]; then
   echo "${weather_city} ${icon_snow} ${weather_temp}${symbol_celsius}"
elif [[ "$(get_weather "${weather_main}" "Rain")" ]] || [[ "$(get_weather "${WEATHER_MAIN}" "Drizzle")" ]]; then
   echo "${weather_city} ${icon_rainy} ${weather_temp}${symbol_celsius}"
elif [[ "$(get_weather "${weather_main}" "Cloud")" ]]; then
   echo "${weather_city} ${icon_cloudy} ${COLOR}${weather_temp}${symbol_celsius}"
elif [[ "$(get_weather "${weather_main}" "Clear")" ]]; then
   echo "${weather_city} ${icon_sunny} ${weather_temp}${symbol_celsius}"
elif [[ "$(get_weather "${weather_main}" "Fog")" ]] || [[ "$(get_weather "${WEATHER_MAIN}" "Mist")" ]]; then
   echo "${weather_city} ${icon_fog} ${weather_temp}${symbol_celsius}"
elif [[ $(get_weather "${weather_main}" "Storm") ]] || [[ $(get_weather "${WEATHER_MAIN}" "storm") ]]; then
   echo "${weather_city} ${icon_storm} ${weather_temp}${symbol_celsius}"
else
   echo "${weather_city} ${weather_main} ${weather_temp}${symbol_celsius}"
fi

