#!/bin/bash
#
# Display the focused window
#

active_win=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2)

if [[ -n "${active_win}" ]]; then
  echo "${active_win}"
fi
