#!/bin/sh
#
# Rofi general menu (centralize all rofi menus)
#

window="📂 Window"
ssh="🔒 Ssh"
drun="🛠️ Applications"
http="🌍 Http"
clipboard="📋 Clipboard"
disp="💻 Display"
power="🔌 Power Management"
#network="🖧 Network Manager"
mount="📥 Mount Devices"
umount="📤 Unmount Devices"
calc="🖩 Calculator"

options="${window},${ssh},${drun},${http}, \
${clipboard},${disp},${power}, \
${mount},${umount},${calc} \
"

launch="$(rofiprompt "Choose option" "${options}")"
case "${launch}" in
   "${window}")
      "${SCRIPTS}"/rofi/rofiwindow
      ;;
   "${ssh}")
      "${SCRIPTS}"/rofi/rofissh
      ;;
   "${drun}")
      "${SCRIPTS}"/rofi/rofidrun
      ;;
   "${http}") # Depends: PACMAN: surf
      "${SCRIPTS}"/rofi/rofisurf
      ;;
   "${clipboard}") # Depends: AUR:rofi-greenclip
      "${SCRIPTS}"/rofi/roficlip
      ;;
   "${network}") # Depends: AUR: networkmanager-dmenu-git
      networkmanager_dmenu
      ;;
   "${disp}")
      "${SCRIPTS}"/rofi/rofidisplay
      ;;
   "${power}")
      "${SCRIPTS}"/rofi/rofipower
      ;;
   "${mount}")
      "${SCRIPTS}"/rofi/rofimount
      ;;
   "${umount}")
      "${SCRIPTS}"/rofi/rofiumount
      ;;
   "${calc}") # Depends: AUR:rofi-calc
      "${SCRIPTS}"/rofi/roficalc
      ;;
   *)
      exit 1
      ;;
esac
