#!/bin/sh
#
# Insert parameters separated by ',' or any separator you want
# Specify the separator if you don't want the default one ','
# Returns the chosen param
#

separator=","

if [ -n "$2" ] && [ -z "$3" ]; then
   result="$(echo "$2" | rofi -no-fixed-num-lines -dmenu -sep "$separator" -i -p "$1" | tr -d '\r\n')"
elif [ -n "$2" ] && [ -n "$3" ]; then
   result="$(echo "$2" | rofi -no-fixed-num-lines -dmenu -sep "$3" -i -p "$1" | tr -d '\r\n')"
else
   result="$(rofi -no-fixed-num-lines -dmenu -i -p "$1" | tr -d '\r\n')"
fi

echo "${result}"
