#!/bin/bash
#
# Creates symlinks for all the scripts in $BIN path(check .profile)
#
#

for entry in $(find "${SCRIPTS}" -type f -not -path "${SCRIPTS}/.git/*"); do
   if [[ $(file --mime-type -b ${entry}) != "text/plain" && "$(basename ${entry})" != "tags" ]]; then
      echo $(basename "${entry}")
      ln -sf "${entry}" "${BIN}"/$(basename "${entry}")
   fi
done

