#!/bin/bash
#
# Suspend session timer.
# Close the network connection before suspending the user session
# Parameters:
#  - param1: <int>h/<int>m/<int>s
#  - param2: sudo password

input="$(echo "$1" | sed 's/[0-9]*//g')"

if [[ -n "$1" && -n "$2" ]] && [[ "${input}" = "h" || "${input}" = "m" || "${input}" = "s" ]]; then
   suspend_time="$(echo "$1" | sed -e 's/[^0-9]*//g')"
   if [[ "$1" = *"h" ]]; then
      dunstify "Your session will be suspended in " "$(printf "${suspend_time} hour(s)")"
   elif [[ "$1" = *"m" ]]; then
      dunstify "Your session will be suspended in " "$(printf "${suspend_time} minute(s)")"
   elif [[ "$1" = *"s" ]]; then
      dunstify "Your session will be suspended in " "$(printf "${suspend_time} second(s)")"
   fi
   sleep "$1";echo "$2" | sudo -S togglenet off;systemctl suspend
else
   echo "Please insert some valid arguments like: 1h, 1m, 1s and password ..."
fi
