#!/bin/bash
#
# Perform a screenshot and save the file to the below dir location
# Parameters:
#  - param1: -e  = all display
#  - param2: -ue = focused window
#

dir="/home/teddy/Pictures/screenshots"

if [[ ! -d "${dir}" ]]; then
   mkdir -p "${dir}"
fi

if [[ "$1" = "-e" ]]; then
   scrot "$1" 'mv $f /home/teddy/Pictures/screenshots'
   dunstify "Screenshot taken !" "Check your $HOME/Pictures/screenshots."
fi

if [[ "$1" = "-ue" ]]; then
   scrot "$1" 'mv $f /home/teddy/Pictures/screenshots'
   dunstify "Screenshot taken !" "Check your $HOME/Pictures/screenshots."
fi


