#!/bin/bash
#
# Toggle network connection on/off
# Also mount/unmount driver
# Parameters:
#  - param1: on/off
#

wire="enp7s0f1"
wifi="wlp0s20f3"
driver="r8168"

if [[ "${1}" = "off"  ]]; then
   systemctl stop NetworkManager &
   ip link set "${wire}" down &
   modprobe -r "${driver}"
elif [[ "${1}" = "on" ]]; then
   modprobe "${driver}"
   ip link set "${wire}" up &
   systemctl start NetworkManager
fi
