#!/bin/bash
#
# Move selected window to bottom/top right/left of the screen
# The window will take up no more than a third of the width or height of the screen.
#

declare -r CURRENT_WIN=$(xdotool getwindowfocus)
declare -r NEW_WIDTH=$(($(xdotool getdisplaygeometry | awk '{print $2}') / 3))
declare -r NEW_HEIGHT=$(($(xdotool getdisplaygeometry | awk '{print $1}') / 3))

main()
{
   if [[ $# == 0 ]]; then
      throwerror "$0"
      exit 1
   fi

   parseparams "h" "help,bottomleft,bottomright,topleft,topright"
   while true; do
      case "$1" in
         -h|--help)
            show_help;
            exit 0
            ;;
         --bottomleft)
            bottom_left
            exit 0
            ;;
         --bottomright)
            bottom_right
            exit 0
            ;;
         --topleft)
            top_left
            exit 0
            ;;
         --topright)
            top_right
            exit 0
            ;;
         *)
            throwerror "$0" "$1"
            exit 1
            ;;
      esac
   done
}

bottom_left()
{
   xdotool windowsize "${CURRENT_WIN}" ${NEW_HEIGHT} ${NEW_WIDTH}

   local size=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')
   local vertical=$(($(xdotool getdisplaygeometry | awk '{print $2}') - ${size}))

   xdotool windowmove "${CURRENT_WIN}" 0 ${vertical}
}

bottom_right()
{
   xdotool windowsize "${CURRENT_WIN}" ${NEW_HEIGHT} ${NEW_WIDTH}

   local size=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')
   local width=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | grep -o " [0-9]*")

   local vertical=$(($(xdotool getdisplaygeometry | awk '{print $2}') - ${size}))
   local horizontal=$(($(xdotool getdisplaygeometry | awk '{print $1}') - ${width}))

   xdotool windowmove "${CURRENT_WIN}" ${horizontal} ${vertical}
}

top_left()
{
   xdotool windowsize "${CURRENT_WIN}" ${NEW_HEIGHT} ${NEW_WIDTH}

   local size=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')
   local vertical=$(($(xdotool getdisplaygeometry | awk '{print $2}') - ${size}))

   xdotool windowmove "${CURRENT_WIN}" 0 22
}

top_right()
{
   xdotool windowsize "${CURRENT_WIN}" ${NEW_HEIGHT} ${NEW_WIDTH}

   local size=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | sed -e 's/x/ /g' | awk '{print $3}')
   local width=$(xdotool getwindowgeometry "${CURRENT_WIN}" | grep Geometry | grep -o " [0-9]*")

   local vertical=$(($(xdotool getdisplaygeometry | awk '{print $2}') - ${size}))
   local horizontal=$(($(xdotool getdisplaygeometry | awk '{print $1}') - ${width}))

   xdotool windowmove "${CURRENT_WIN}" ${horizontal} 22
}

show_help()
{
cat <<-END
Usage: $(basename $0) <cmd>

Move selected window to bottom/top right/left of the screen.
The window will take up no more than a third of the width or height of the screen.

Options:
      --bottomright = move the window to bottom right of the screen
      --bottomleft  = move the window to bottom left of the screen
      --topright    = move the window to top right of the screen
      --topleft     = move the window to top left of the screen
   -h --help     = show help
END
}

#--------------------------------------------------------------------

main "$@"
