#!/bin/bash
#
# Add torrent to transmission-daemon automatically when
# torrent file is downloaded using magnet link.
# Requires a default torrent client to be configured in mimeapps.list
# Ex:
# x-scheme-handler/magnet=transmission.desktop;
# application/x-bittorrent=transmission.desktop;
#


main()
{
   local proc_trans_da=$(pgrep -x transmission-da)

   if [[ ${proc_trans_da} ]]; then
      transmission-daemon
      dunstify "Starting transmission daemon ..."
      sleep 3
      transmission-remote -a "$@"
      dunstify "Torrent added."
   fi
}

#------------------------------------------------------------------------

main "$@"
