#!/bin/sh
#
# Add torrent to transmission-daemon
#

proc_trans_da=$(pgrep -x transmission-da)

if [ ${proc_trans_da} ]; then
   transmission-daemon
   notify-send "Starting transmission daemon ..." 
   sleep 3
   transmission-remote -a "$@"
   notify-send "Torrent added."
fi
