#!/bin/sh
# Disable screen tearing  ForceFullCompositionPipeline=On

disp_rate=144
disp="$(xrandr | grep HDMI | awk '{print $1}')"
disp_res="$(xrandr | awk '/HDMI/ {getline; print $1}')"
mon_pos="$(xrandr | grep HDMI | awk '{print $4}' | sed 's/\w*x\w*//g')"

if [ "${1}" = "On" ] || [ "${1}" = "Off" ]; then
   nvidia-settings --assign CurrentMetaMode="${disp}:${disp_res}_${disp_rate} ${mon_pos} { ForceFullCompositionPipeline = ${1} }"
   #nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = ${1} }"
else
   echo "Invalid parameter: choose between 'On' or 'Off'."
fi
