#!/bin/bash
#
# Rofi power management menu
#

reboot=" Reboot"
shutdown=" Shutdown"
susp=" Suspend"
lock=" Lock"
log_out=" Log Out"

options="${reboot},${shutdown},${susp},${lock},${log_out}"
locker=betterlockscreen
locker_img="${HOME}/.config/i3/lockscreen"
launch="$(rofiprompt "Choose option" "${options}")"

check_locker()
{
   if [[ ! -d "${HOME}/.cache/i3lock" ]]; then
      ${locker} -u "${locker_img}"
   fi
}

case "${launch}" in
   "${reboot}")
      systemctl reboot
      ;;
   "${shutdown}")
      systemctl poweroff
      ;;
   "${susp}")
      ${locker} -s
      ;;
   "${lock}")
      check_locker
      ${locker} -l
      ;;
   "${log_out}")
      i3-msg exit
      ;;
   *)
      exit 1
      ;;
esac

