#!/bin/bash
#
# Rofi prompt dialog.
#
# Insert parameters separated by ',' or any separator you want - default mode
# Specify the separator if you don't want the default one
# Returns the chosen param
# Parameters:
#  - param1: choices separated by chosen separator
#  - param1: prompt text
#  - param3: chosen separator (optional)
# Ex:
# rofiprompt "Rendering text" "<optional separator>" "opt1,opt2,opt3"
#

separator=","

if [[ -n "$2" ]] && [[ -z "$3" ]]; then
   result="$(echo "$2" | rofi -no-fixed-num-lines -xoffset 0 -yoffset -100 -dmenu -sep "$separator" -i -p "$1" | tr -d '\r\n')"
elif [[ -n "$2" ]] && [[ -n "$3" ]]; then
   result="$(echo "$2" | rofi -no-fixed-num-lines -xoffset 0 -yoffset -100 -dmenu -sep "$3" -i -p "$1" | tr -d '\r\n')"
else
   result="$(rofi -no-fixed-num-lines -xoffset 0 -yoffset -100 -dmenu -i -p "$1" | tr -d '\r\n')"
fi

echo "${result}"
