#!/bin/bash
#
# Search the desired info on the web
#
# Dependency: surf or chromium or any browser
#

search="$(rofi -lines 0 -dmenu -i -p 'Search')"
links=(
"http://www.google.com/search?q=${search}"
"https://duckduckgo.com/?q=${search}"
)

if [[ ! -z "${search}" ]]; then
   #surf "${search_links[1]}"
   ${BROWSER} "${links[0]}"
fi
